import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { HeaderComponent } from "./ui/Header/Header";
import { FooterComponent } from "./ui/Footer/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nostromo | Compra rapido y seguro.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between">
          <HeaderComponent />
          {children}
          <FooterComponent></FooterComponent>
        </main>
      </body>
    </html>
  );
}
